export interface CountrySpec {
  id: string
  name: string
  flag: string
  slug: string
  widthMm: number
  heightMm: number
  widthPx: number
  heightPx: number
  dpi: number
  background: string
  bgColor: string        // hex color for auto-fill, e.g. '#ffffff', '#d0d0d0', '#cc0000'
  bgColorLabel: string   // human label, e.g. 'White', 'Light grey', 'Red'
  requirements: string[]
  seoTitle: string
  seoDescription: string
  h1: string
  faq: { q: string; a: string }[]
}

export const countries: CountrySpec[] = [
  {
    id: 'us',
    name: 'United States',
    flag: '🇺🇸',
    slug: 'us-passport-photo',
    widthMm: 51,
    heightMm: 51,
    widthPx: 600,
    heightPx: 600,
    dpi: 300,
    background: 'White or off-white',
    bgColor: '#ffffff',
    bgColorLabel: 'White',
    requirements: [
      'Size: 2×2 inches (51×51 mm)',
      'Printed at 300 DPI minimum',
      'Plain white or off-white background',
      'Neutral facial expression, mouth closed',
      'Both eyes open and clearly visible',
      'No glasses (since 2016)',
      'Head centered, facing camera directly',
      'Face must cover 70–80% of the frame',
      'Taken within the last 6 months',
    ],
    seoTitle: 'Free US Passport Photo Maker | 2×2 inch | No Watermark | Free',
    seoDescription:
      'Create a compliant US passport photo online for free. Correct 2×2 inch size, white background. No registration, no watermark. Download JPG or print-ready PDF instantly.',
    h1: 'Free US Passport Photo Maker',
    faq: [
      {
        q: 'What size is a US passport photo?',
        a: 'US passport photos must be exactly 2×2 inches (51×51 mm). When printed at 300 DPI that equals 600×600 pixels. Our tool automatically outputs the correct size.',
      },
      {
        q: 'What background color is required for US passport photos?',
        a: 'The background must be plain white or off-white. No patterns, shadows, or other people should appear in the background.',
      },
      {
        q: 'Can I wear glasses in my US passport photo?',
        a: 'No. Since November 2016, the US Department of State does not accept passport photos with glasses, even prescription glasses.',
      },
      {
        q: 'How recent does my passport photo need to be?',
        a: 'Your photo must have been taken within the last 6 months and must reflect your current appearance.',
      },
      {
        q: 'Can I use this photo for a US visa application?',
        a: 'Yes. The 2×2 inch format is accepted for most US visa applications as well as for Global Entry, TSA PreCheck, and other government programs.',
      },
      {
        q: 'Is my photo uploaded to your servers?',
        a: 'No. All processing happens entirely in your browser using JavaScript. Your photo never leaves your device.',
      },
    ],
  },
  {
    id: 'uk',
    name: 'United Kingdom',
    flag: '🇬🇧',
    slug: 'uk-passport-photo',
    widthMm: 35,
    heightMm: 45,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'Plain cream or light grey',
    bgColor: '#f0ede8',
    bgColorLabel: 'Cream',
    requirements: [
      'Size: 35×45 mm',
      'Plain cream or light grey background',
      'Neutral expression, mouth closed',
      'Eyes open and clearly visible',
      'No glasses',
      'Face must take up 70–80% of the frame',
      'Taken within the last month',
      'No head covering (unless for religious reasons)',
    ],
    seoTitle: 'Free UK Passport Photo Maker | 35×45mm | No Watermark | Free',
    seoDescription:
      'Create a compliant UK passport photo online for free. Correct 35×45mm size. No registration, no watermark. Download JPG or print-ready PDF instantly.',
    h1: 'Free UK Passport Photo Maker',
    faq: [
      {
        q: 'What size is a UK passport photo?',
        a: 'UK passport photos must be 35 mm wide and 45 mm tall. Our tool outputs the correct pixel dimensions for printing at 300 DPI.',
      },
      {
        q: 'What background is required for a UK passport photo?',
        a: 'The background must be plain cream or light grey. It must have no patterns or shadows.',
      },
      {
        q: 'Can I wear glasses in my UK passport photo?',
        a: 'No. HM Passport Office stopped accepting photos with glasses in 2018.',
      },
      {
        q: 'How recent does my UK passport photo need to be?',
        a: 'UK passport photos should be taken within the last month and must show your current appearance.',
      },
      {
        q: 'Can I smile in my UK passport photo?',
        a: 'You should have a neutral expression with your mouth closed. A slight natural smile may be acceptable, but a broad smile is not.',
      },
      {
        q: 'Is my photo uploaded to your servers?',
        a: 'No. All processing happens entirely in your browser. Your photo never leaves your device.',
      },
    ],
  },
  {
    id: 'canada',
    name: 'Canada',
    flag: '🇨🇦',
    slug: 'canada-passport-photo',
    widthMm: 50,
    heightMm: 70,
    widthPx: 591,
    heightPx: 827,
    dpi: 300,
    background: 'White',
    bgColor: '#ffffff',
    bgColorLabel: 'White',
    requirements: [
      'Size: 50×70 mm',
      'Plain white background',
      'Neutral expression, mouth closed',
      'Both eyes open and clearly visible',
      'No glasses',
      'Head centered and straight',
      'Face height between 31–36 mm from chin to crown',
      'Taken within the last 6 months',
    ],
    seoTitle: 'Free Canada Passport Photo Maker | 50×70mm | No Watermark | Free',
    seoDescription:
      'Create a compliant Canadian passport photo online for free. Correct 50×70mm size. No registration, no watermark. Download JPG or print-ready PDF instantly.',
    h1: 'Free Canada Passport Photo Maker',
    faq: [
      {
        q: 'What size is a Canadian passport photo?',
        a: 'Canadian passport photos must be 50 mm wide and 70 mm tall, with the face occupying 31–36 mm of the height.',
      },
      {
        q: 'What background is required for a Canadian passport photo?',
        a: 'The background must be plain white with no patterns or shadows.',
      },
      {
        q: 'Can I wear glasses in my Canadian passport photo?',
        a: 'No. Immigration, Refugees and Citizenship Canada (IRCC) does not accept photos taken with glasses.',
      },
      {
        q: 'Can I use this photo for a Canadian visa?',
        a: 'Yes. The 50×70mm format is also used for Canadian visas and permanent resident cards.',
      },
      {
        q: 'How recent must the photo be?',
        a: 'The photo must have been taken within the last 6 months and must represent your current appearance.',
      },
      {
        q: 'Is my photo uploaded to your servers?',
        a: 'No. All processing happens entirely in your browser. Your photo never leaves your device.',
      },
    ],
  },
  {
    id: 'australia',
    name: 'Australia',
    flag: '🇦🇺',
    slug: 'australia-passport-photo',
    widthMm: 35,
    heightMm: 45,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'Plain white or light grey',
    bgColor: '#ffffff',
    bgColorLabel: 'White',
    requirements: [
      'Size: 35×45 mm',
      'Plain white or light grey background',
      'Neutral expression, mouth closed',
      'Eyes open and clearly visible',
      'No glasses',
      'Face must take up at least 75–80% of the frame',
      'Taken within the last 6 months',
    ],
    seoTitle: 'Free Australian Passport Photo Maker | 35×45mm | No Watermark | Free',
    seoDescription:
      'Create a compliant Australian passport photo online for free. Correct 35×45mm size. No registration, no watermark. Download JPG or print-ready PDF instantly.',
    h1: 'Free Australian Passport Photo Maker',
    faq: [
      {
        q: 'What size is an Australian passport photo?',
        a: 'Australian passport photos must be 35 mm wide and 45 mm tall.',
      },
      {
        q: 'What background is required?',
        a: 'The background must be plain white or light grey, without patterns or shadows.',
      },
      {
        q: 'Can I wear glasses?',
        a: 'No. The Australian Passport Office does not accept photos with glasses.',
      },
      {
        q: 'How recent does the photo need to be?',
        a: 'The photo must have been taken within the last 6 months.',
      },
      {
        q: 'Can I use this for an Australian visa?',
        a: 'Yes. The 35×45mm format is accepted for Australian visas and the ImmiAccount portal.',
      },
      {
        q: 'Is my photo uploaded to any server?',
        a: 'No. All processing happens entirely in your browser. Your photo never leaves your device.',
      },
    ],
  },
  {
    id: 'india',
    name: 'India',
    flag: '🇮🇳',
    slug: 'india-passport-photo',
    widthMm: 35,
    heightMm: 45,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'Plain white',
    bgColor: '#ffffff',
    bgColorLabel: 'White',
    requirements: [
      'Size: 35×45 mm',
      'Plain white background',
      'Neutral expression, mouth closed',
      'Both eyes open and clearly visible',
      'No glasses',
      'Head centered, facing camera directly',
      'Face should cover 70–80% of frame',
      'Taken within the last 6 months',
      'No shadows on face or background',
    ],
    seoTitle: 'Free India Passport Photo Maker | 35×45mm | No Watermark | Free',
    seoDescription:
      'Create a compliant Indian passport photo online for free. Correct 35×45mm size. No registration, no watermark. Download JPG or print-ready PDF instantly.',
    h1: 'Free India Passport Photo Maker',
    faq: [
      {
        q: 'What size is an Indian passport photo?',
        a: 'Indian passport photos must be 35 mm wide and 45 mm tall with a plain white background.',
      },
      {
        q: 'Can I wear glasses in my Indian passport photo?',
        a: 'No. The Ministry of External Affairs does not accept passport photos with glasses.',
      },
      {
        q: 'Can I wear a head covering?',
        a: 'Head coverings are only permitted for religious reasons. The face must be fully visible.',
      },
      {
        q: 'How recent must the photo be?',
        a: 'The photo must be taken within the last 6 months.',
      },
      {
        q: 'Can I use this photo for an Indian visa application?',
        a: 'Yes. The 35×45mm format is accepted for all Indian visa categories.',
      },
      {
        q: 'Is my photo uploaded to your servers?',
        a: 'No. All processing is done locally in your browser. Your photo never leaves your device.',
      },
    ],
  },
  {
    id: 'schengen',
    name: 'Schengen / EU',
    flag: '🇪🇺',
    slug: 'schengen-visa-photo',
    widthMm: 35,
    heightMm: 45,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'Plain white or light grey',
    bgColor: '#ffffff',
    bgColorLabel: 'White',
    requirements: [
      'Size: 35×45 mm',
      'Plain white or light grey background',
      'Neutral expression, mouth closed',
      'Eyes open and clearly visible',
      'No glasses',
      'Head straight and centered',
      'Face must cover 70–80% of the frame',
      'Taken within the last 6 months',
      'ICAO biometric compliant',
    ],
    seoTitle: 'Free Schengen Visa Photo Maker | 35×45mm | No Watermark | Free',
    seoDescription:
      'Create a compliant Schengen visa photo online for free. Correct 35×45mm biometric size for all EU countries. No registration, no watermark. Instant JPG or PDF download.',
    h1: 'Free Schengen Visa Photo Maker',
    faq: [
      {
        q: 'What size is a Schengen visa photo?',
        a: 'Schengen visa photos must be 35 mm wide and 45 mm tall. This standard applies to all 27 Schengen area countries.',
      },
      {
        q: 'Which countries accept the Schengen photo format?',
        a: 'All 27 EU Schengen countries including Germany, France, Italy, Spain, Netherlands, Belgium, Austria, Switzerland, and others.',
      },
      {
        q: 'What background color is required?',
        a: 'The background must be plain white or very light grey. No textures, patterns, or shadows.',
      },
      {
        q: 'Can I wear glasses in a Schengen visa photo?',
        a: 'No. As of 2015, glasses are not permitted in biometric passport or visa photos within the EU.',
      },
      {
        q: 'Can I use this photo for a German, French, or Italian passport?',
        a: 'Yes. The 35×45mm biometric format is the standard for all EU national passports and Schengen visas.',
      },
      {
        q: 'Is my photo uploaded to your servers?',
        a: 'No. All processing happens entirely in your browser. Your photo never leaves your device.',
      },
    ],
  },
  {
    id: 'uae',
    name: 'UAE',
    flag: '🇦🇪',
    slug: 'uae-passport-photo',
    widthMm: 40,
    heightMm: 60,
    widthPx: 472,
    heightPx: 709,
    dpi: 300,
    background: 'White',
    bgColor: '#ffffff',
    bgColorLabel: 'White',
    requirements: [
      'Size: 40×60 mm',
      'Plain white background',
      'Neutral expression, mouth closed',
      'Both eyes open and clearly visible',
      'No glasses',
      'Head centered and straight',
      'Taken within the last 6 months',
      'No shadows on face or background',
    ],
    seoTitle: 'Free UAE Passport Photo Maker | 40×60mm | No Watermark | Free',
    seoDescription:
      'Create a compliant UAE passport photo online for free. Correct 40×60mm size. No registration, no watermark. Download JPG or print-ready PDF instantly.',
    h1: 'Free UAE Passport Photo Maker',
    faq: [
      {
        q: 'What size is a UAE passport photo?',
        a: 'UAE passport photos must be 40 mm wide and 60 mm tall with a plain white background.',
      },
      {
        q: 'Can I wear glasses in my UAE passport photo?',
        a: 'No. The UAE Federal Authority for Identity and Citizenship does not accept photos with glasses.',
      },
      {
        q: 'Can I use this photo for UAE visa applications?',
        a: 'Yes. The 40×60mm format is accepted for UAE residence visas, entry permits, and Emirates ID applications.',
      },
      {
        q: 'Can women wear hijab in a UAE passport photo?',
        a: 'Yes, a hijab is permitted as long as the face is fully visible from forehead to chin.',
      },
      {
        q: 'How recent must the photo be?',
        a: 'The photo must be taken within the last 6 months and reflect your current appearance.',
      },
      {
        q: 'Is my photo uploaded to your servers?',
        a: 'No. All processing is done locally in your browser. Your photo never leaves your device.',
      },
    ],
  },
]

export const extraCountries: CountrySpec[] = [
  {
    id: 'germany',
    name: 'Germany',
    flag: '🇩🇪',
    slug: 'germany-passport-photo',
    widthMm: 35,
    heightMm: 45,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'Plain light grey or white',
    bgColor: '#e0e0e0',
    bgColorLabel: 'Light grey',
    requirements: [
      'Size: 35×45 mm (biometric)',
      'Plain light grey or white background',
      'Neutral expression, mouth closed',
      'Eyes open, looking directly at camera',
      'No glasses (since 2017)',
      'Head centered and straight',
      'Face must cover 70–80% of the frame',
      'Taken within the last 6 months',
      'ICAO biometric compliant',
    ],
    seoTitle: 'Free Germany Passport Photo Maker | 35×45mm Biometrisch | No Watermark | Free',
    seoDescription:
      'Create a compliant German biometric passport photo (Passfoto) online for free. Correct 35×45mm size. No registration, no watermark. Download JPG or PDF instantly.',
    h1: 'Free Germany Passport Photo Maker',
    faq: [
      { q: 'What size is a German passport photo?', a: 'German passport photos (Biometrisches Passfoto) must be 35 mm wide and 45 mm tall, conforming to the ICAO biometric standard.' },
      { q: 'What background is required for a German passport photo?', a: 'The background must be plain light grey or white, without patterns or shadows.' },
      { q: 'Can I wear glasses in a German passport photo?', a: 'No. Since 2017, glasses are not permitted in German biometric passport photos.' },
      { q: 'Is this format also valid for a German ID card (Personalausweis)?', a: 'Yes. The 35×45mm biometric format is used for both the German passport (Reisepass) and the national ID card (Personalausweis).' },
      { q: 'How recent must the photo be?', a: 'The photo must have been taken within the last 6 months.' },
      { q: 'Is my photo uploaded to your servers?', a: 'No. All processing happens entirely in your browser. Your photo never leaves your device.' },
    ],
  },
  {
    id: 'japan',
    name: 'Japan',
    flag: '🇯🇵',
    slug: 'japan-visa-photo',
    widthMm: 35,
    heightMm: 45,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'Plain white',
    bgColor: '#ffffff',
    bgColorLabel: 'White',
    requirements: [
      'Size: 35×45 mm',
      'Plain white background',
      'Neutral expression, mouth closed',
      'Both eyes open and visible',
      'No glasses',
      'Head centered, no tilt',
      'Face height 32–36 mm from chin to crown',
      'Taken within the last 6 months',
      'No shadows on face or background',
    ],
    seoTitle: 'Free Japan Visa Photo Maker | 35×45mm | No Watermark | Free',
    seoDescription:
      'Create a compliant Japan visa or passport photo online for free. Correct 35×45mm size, white background. No registration, no watermark. Instant download.',
    h1: 'Free Japan Visa & Passport Photo Maker',
    faq: [
      { q: 'What size is a Japan visa photo?', a: 'Japan visa and passport photos must be 35 mm wide and 45 mm tall, with the face taking up 32–36 mm of the height.' },
      { q: 'What background is required?', a: 'The background must be plain white without any patterns, shadows, or objects.' },
      { q: 'Can I wear glasses?', a: 'No. The Japanese Ministry of Foreign Affairs does not accept photos with glasses for visa and passport applications.' },
      { q: 'Can I use this photo for a Japan tourist visa?', a: 'Yes. This format is accepted for all Japan visa categories including tourist (temporary visitor), work, and student visas.' },
      { q: 'How recent must the photo be?', a: 'The photo must be taken within the last 6 months.' },
      { q: 'Is my photo uploaded to your servers?', a: 'No. All processing happens in your browser. Your photo never leaves your device.' },
    ],
  },
  {
    id: 'brazil',
    name: 'Brazil',
    flag: '🇧🇷',
    slug: 'brazil-passport-photo',
    widthMm: 50,
    heightMm: 70,
    widthPx: 591,
    heightPx: 827,
    dpi: 300,
    background: 'Plain white',
    bgColor: '#ffffff',
    bgColorLabel: 'White',
    requirements: [
      'Size: 50×70 mm',
      'Plain white background',
      'Neutral expression, mouth closed',
      'Both eyes open and visible',
      'No glasses',
      'Head centered and straight',
      'Face must occupy 70–80% of the frame',
      'Taken within the last 6 months',
    ],
    seoTitle: 'Free Brazil Passport Photo Maker | 50×70mm | No Watermark | Free',
    seoDescription:
      'Create a compliant Brazilian passport photo online for free. Correct 50×70mm size. No registration, no watermark. Download JPG or print-ready PDF instantly.',
    h1: 'Free Brazil Passport Photo Maker',
    faq: [
      { q: 'What size is a Brazilian passport photo?', a: 'Brazilian passport photos must be 50 mm wide and 70 mm tall with a plain white background.' },
      { q: 'Can I wear glasses?', a: 'No. The Brazilian Federal Police does not accept passport photos with glasses.' },
      { q: 'Can I use this for a Brazilian visa application?', a: 'Yes. The 50×70mm format is accepted for Brazilian passports and visas.' },
      { q: 'What background is required?', a: 'The background must be plain white, without patterns or shadows.' },
      { q: 'How recent must the photo be?', a: 'The photo must have been taken within the last 6 months.' },
      { q: 'Is my photo uploaded to your servers?', a: 'No. Everything is processed locally in your browser.' },
    ],
  },
  {
    id: 'mexico',
    name: 'Mexico',
    flag: '🇲🇽',
    slug: 'mexico-passport-photo',
    widthMm: 35,
    heightMm: 45,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'Plain white',
    bgColor: '#ffffff',
    bgColorLabel: 'White',
    requirements: [
      'Size: 35×45 mm',
      'Plain white background',
      'Neutral expression, mouth closed',
      'Both eyes open and clearly visible',
      'No glasses',
      'Head straight and centered',
      'Face must cover 70–80% of the frame',
      'Taken within the last 6 months',
    ],
    seoTitle: 'Free Mexico Passport Photo Maker | 35×45mm | No Watermark | Free',
    seoDescription:
      'Create a compliant Mexican passport photo online for free. Correct 35×45mm size. No registration, no watermark. Download JPG or print-ready PDF instantly.',
    h1: 'Free Mexico Passport Photo Maker',
    faq: [
      { q: 'What size is a Mexican passport photo?', a: 'Mexican passport photos must be 35 mm wide and 45 mm tall with a plain white background.' },
      { q: 'Can I wear glasses?', a: 'No. The Secretaría de Relaciones Exteriores does not accept passport photos with glasses.' },
      { q: 'Can I use this for Mexican visa applications?', a: 'Yes. The 35×45mm format is accepted for Mexican passports and most visa applications.' },
      { q: 'How recent must the photo be?', a: 'The photo must have been taken within the last 6 months.' },
      { q: 'What background is required?', a: 'Plain white, without any patterns, shadows, or objects in the background.' },
      { q: 'Is my photo uploaded to your servers?', a: 'No. All processing happens in your browser. Your photo never leaves your device.' },
    ],
  },
  {
    id: 'china',
    name: 'China',
    flag: '🇨🇳',
    slug: 'china-visa-photo',
    widthMm: 33,
    heightMm: 48,
    widthPx: 390,
    heightPx: 567,
    dpi: 300,
    background: 'Plain white',
    bgColor: '#ffffff',
    bgColorLabel: 'White',
    requirements: [
      'Size: 33×48 mm (unique format)',
      'Plain white background',
      'Neutral expression, mouth closed',
      'Both eyes open and clearly visible',
      'No glasses',
      'Head straight, no tilt',
      'Face must cover 60–80% of the frame',
      'Taken within the last 6 months',
      'No shadows on face or background',
    ],
    seoTitle: 'Free China Visa Photo Maker | 33×48mm | No Watermark | Free',
    seoDescription:
      'Create a compliant China visa photo online for free. Correct 33×48mm size — unique Chinese format. No registration, no watermark. Instant download.',
    h1: 'Free China Visa Photo Maker',
    faq: [
      { q: 'What size is a China visa photo?', a: 'China visa photos have a unique format: 33 mm wide and 48 mm tall. This differs from the standard 35×45mm used by most countries.' },
      { q: 'What background is required for a China visa photo?', a: 'The background must be plain white, without patterns, shadows, or other people.' },
      { q: 'Can I wear glasses?', a: 'No. The Chinese embassy does not accept visa photos with glasses.' },
      { q: 'Is this format valid for a Chinese passport?', a: 'The 33×48mm format is used for Chinese visas. Chinese passport requirements may differ slightly — always verify with the consulate.' },
      { q: 'How recent must the photo be?', a: 'The photo must have been taken within the last 6 months.' },
      { q: 'Is my photo uploaded to your servers?', a: 'No. All processing happens in your browser. Your photo never leaves your device.' },
    ],
  },
]

export const newCountries: CountrySpec[] = [
  {
    id: 'indonesia',
    name: 'Indonesia',
    flag: '🇮🇩',
    slug: 'indonesia-passport-photo',
    widthMm: 51,
    heightMm: 51,
    widthPx: 600,
    heightPx: 600,
    dpi: 300,
    background: 'Red',
    bgColor: '#cc0000',
    bgColorLabel: 'Red',
    requirements: [
      'Size: 51×51 mm (2×2 inch)',
      'Plain RED background — mandatory for Indonesian passport',
      'Neutral expression, mouth closed',
      'Both eyes open and clearly visible',
      'No glasses',
      'Head centered and straight',
      'Face must cover 70–80% of frame',
      'No shadows on face or background',
      'Taken within the last 6 months',
    ],
    seoTitle: 'Free Indonesia Passport Photo Maker | Red Background | No Watermark | Free',
    seoDescription:
      'Create a compliant Indonesian passport photo online for free. Correct 51×51mm size with mandatory red background. No registration, no watermark. Instant download.',
    h1: 'Free Indonesia Passport Photo Maker',
    faq: [
      { q: 'What background color is required for Indonesian passport photos?', a: 'Indonesian passport photos require a plain RED background — this is unique and mandatory. It differs from most countries that use white or grey.' },
      { q: 'What size is an Indonesian passport photo?', a: 'Indonesian passport photos must be 51×51 mm (2×2 inch, same as the US format), but with a red background instead of white.' },
      { q: 'Does the tool automatically apply the red background?', a: 'Yes. Use the "Apply Red Background" button to automatically fill the background with the correct red color.' },
      { q: 'Can I use a white background for an Indonesian visa?', a: 'For visa applications (e-visa), a white background is accepted. The red background is specifically required for physical Indonesian passport applications.' },
      { q: 'Can I wear glasses?', a: 'No. Indonesian passport regulations do not accept photos with glasses.' },
      { q: 'Is my photo uploaded to your servers?', a: 'No. All processing happens in your browser. Your photo never leaves your device.' },
    ],
  },
  {
    id: 'finland',
    name: 'Finland',
    flag: '🇫🇮',
    slug: 'finland-passport-photo',
    widthMm: 36,
    heightMm: 47,
    widthPx: 425,
    heightPx: 555,
    dpi: 300,
    background: 'Plain grey',
    bgColor: '#d0d0d0',
    bgColorLabel: 'Light grey',
    requirements: [
      'Size: 36×47 mm (unique Finnish format)',
      'Plain grey background — lighter for dark hair, medium for light hair',
      'Neutral expression, mouth closed',
      'Both eyes open and clearly visible',
      'No glasses',
      'Head centered and straight',
      'Face must cover 70–80% of frame',
      'Taken within the last 6 months',
      'ICAO biometric compliant',
    ],
    seoTitle: 'Free Finland Passport Photo Maker | 36×47mm Grey Background | No Watermark | Free',
    seoDescription:
      'Create a compliant Finnish passport photo online for free. Unique 36×47mm size with grey background. No registration, no watermark. Instant download.',
    h1: 'Free Finland Passport Photo Maker',
    faq: [
      { q: 'What size is a Finnish passport photo?', a: 'Finnish passport and visa photos have a unique size: 36 mm wide and 47 mm tall. This differs from the standard 35×45mm used by most EU countries.' },
      { q: 'What background color is required for Finnish passport photos?', a: 'Finland requires a plain grey background. The shade can vary — lighter grey for dark hair, medium grey for light hair — to ensure good contrast with your face.' },
      { q: 'Is the Finnish format the same as the Schengen standard?', a: 'No. Finland uses a 36×47mm format with a grey background, while the general Schengen standard is 35×45mm with white background. Always use the Finnish-specific format for Finnish documents.' },
      { q: 'Can I use this photo for a Finnish visa?', a: 'Yes. The 36×47mm grey background format is accepted for Finnish passports, ID cards, and visa applications.' },
      { q: 'Can I wear glasses?', a: 'No. Finnish passport regulations follow the ICAO biometric standard which does not permit glasses.' },
      { q: 'Is my photo uploaded to your servers?', a: 'No. All processing happens in your browser. Your photo never leaves your device.' },
    ],
  },
]

export const allCountries = [...countries, ...extraCountries, ...newCountries]

export const countriesById = Object.fromEntries(allCountries.map((c) => [c.id, c]))

export const defaultCountry = countries[0]
